### ISSUE TITLE
not (yet) working with TB 60.*

### ISSUE THREAD

**Issue by despecial** [Ximi1970/Manually-Sort-Folders#1]
Hoped your fixes would add back the possibility to sort the folders.
But after installing there is still an empty account list and no option to move local folders above the other mail accounts.

Should it already work or are you still working on the fix?

![thunderbird 60 with latest version (04 oct 2018)](https://user-images.githubusercontent.com/4135109/46571885-62c56a00-c97d-11e8-8ad0-c7dc0028c483.png)

**Comment by Ximi1970** [comment]
I thought I had the account sort working but messing around with the folder sort (tab 2) killed it again.
I now will try to create a stable and tested account sort first (tab 1) with the second tab disabled.

Please keep in mind the source tree is very unstable atm. Use it with care...It can wreck your thunderbird account config.
I am just experimenting with the code because there is no decent documentation what so ever for writing thunderbird plugins. There are only small code snippets and obsolete docs available.

If I think it is stable enough and passes some simple tests, I will create a pre release package.

Please be patient, I need to guess and learn a lot :-)

**Comment by despecial** [comment]
Thanks for the quick response. And sure, I will be patient. Guess there are many thankful users if you succeed with the fix for this addon! :)

**Comment by Ximi1970** [comment]
First pre-release is available. Only account sorting for now.

**Comment by Ximi1970** [comment]
Everything should be working now.
But be careful trying it out. Make a backup of your thunderbird config dir.
