### ISSUE TITLE
any chance to make it tb v68 compatible?

### ISSUE THREAD

**Issue by despecial** [Ximi1970/Manually-Sort-Folders#10]
Obviously it should be an easy task:
https://developer.thunderbird.net/add-ons/updates

**Comment by Ximi1970** [comment]
Here you go....

https://github.com/Ximi1970/Manually-Sort-Folders/releases/tag/v2.0.0pre1

And there is nothing easy in TB...
The changes proposed by the TB team are going to kill a lot of plugins just because of security reasons. And this plugin can read and change a lot of mail parameters...
How long access to these parameters are granted, we will see.
